### PR TITLE
NANO currency / error check on verify

### PR DESCRIPTION
**Pull request by jromero**
**Changes**
* Add NANO currency
* Check for error when making verification request

**Motivation**

1. As a new shop owner it would make sense that if the goal in mind is to accept NANO payments using Brainblocks that the currency would also be available. This is by no means a requirement since they can select any currency supported by Brainblocks but it's positive in that it reduces the friction to get up and running.
2. In the first test run of the integration there was a mishap where `response code` was empty. Based on the [Wordpress documentation](https://developer.wordpress.org/reference/functions/wp_remote_get/#return) that would happen if the `$request` was actually of type `WP_Error` which wasn't being checked.

### CODE REVIEW

**Comment by schenkty** [comment]
Hey @jromero, thanks for this PR. I'll have to do a code review before merge but from a glance, it looks good. Our platform used rai as a method to define (1 NANO / 1000000) due to the confusion between NANO and nano. nano and rai are the same 👍

**Comment by jromero** [comment]
@schenkty Thanks! I totally agree with the confusion and it makes complete sense on the technical side to use `rai`. As a matter of fact, it helped me personally.

Nonetheless, the customers will be using `NANO` (at least for some time) so it makes sense that the translation be done in the plugin.

**Comment by jromero** [comment]
I'm looking to clear up my backlog of opened items. I'm curious if there is still a desire to merge this or if it should simply be closed. Thoughts?

**Review by schenkty — APPROVED** [review]

**Comment by schenkty** [comment]
Thanks. Sorry this was missed!

**Pull request merged**
